name: Run scrapping every night

on:
  schedule:
    # Tous les jours à 20:00 UTC (= 22h Paris l'été, 21h l'hiver)
    - cron: "0 20 * * *"
  workflow_dispatch: {}   # Permet de lancer manuellement depuis l'onglet Actions

jobs:
  scrapping-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scrapping script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
        run: python E1_BDD/scrapping.py
