# .github/workflows/train-model.yml
name: train-model

on:
  workflow_run:
    workflows: ["Run scrapping every night"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: train-model
  cancel-in-progress: true

jobs:
  train:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # exécution notebook
          pip install papermill jupyter
          # (optionnel) SHAP peut être lourd/instable en CI
          pip install shap || true

      - name: Train model (execute notebook)
        env:
          MYSQL_URL: ${{ secrets.MYSQL_URL }} 
        run: |
          papermill E3_E4_API_app/model_reco.ipynb E3_E4_API_app/model_reco.out.ipynb

      - name: List produced artifacts
        run: ls -lh E3_E4_API_app/model || true

      - name: Upload output notebook (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: model-training-notebook
          path: E3_E4_API_app/model_reco.out.ipynb
          if-no-files-found: warn

      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure LFS tracking
        run: |
          git lfs install --local
          git lfs track "*.joblib"
          git add .gitattributes

      - name: Stage artifacts through LFS (renormalize)
        run: |
          # Force la conversion en pointeur LFS si nécessaire
          git add --renormalize E3_E4_API_app/model/*.joblib
          # (si tu ajoutes d’autres gros formats un jour, répète ici)

      - name: Verify artifacts are LFS pointers (guard step)
        run: |
          echo "Tracked by LFS:"
          git lfs ls-files || true
          # Échoue si aucun .joblib n'est pris en charge par LFS
          cnt=$(git lfs ls-files | wc -l)
          if [ "$cnt" -eq 0 ]; then
            echo "::error::No LFS-tracked files found. Aborting."
            exit 1
          fi

      - name: Commit & push model artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add E3_E4_API_app/model/*.joblib
          git commit -m "chore(model): update trained artifacts [skip ci]" || echo "nothing to commit"
          git push

