name: Scrape Streaming Catalogs

on:
  workflow_dispatch:   # lancement manuel

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape platforms (France only)
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_COUNTRY: FR
          TMDB_LANGUAGE: fr-FR
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
        run: |
          python E1_BDD/scrapping_platforms.py --reset --scrape
