name: Scrape platforms (direct, no staging)

on:
  schedule:
    - cron: "0 0 5 * *"
  workflow_dispatch:

jobs:
  scrape-platforms:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    strategy:
      fail-fast: false
      matrix:
        platform: [netflix, disney, prime, apple, canal, paramount, hbo, crunchyroll] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run platform scrape (${{ matrix.platform }})
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          TMDB_COUNTRY: FR
          TMDB_LANGUAGE: fr-FR
        run: |
          set -e
          for attempt in 1 2 3; do
            echo "▶️ Attempt $attempt for platform=${{ matrix.platform }}..."
            python E1_BDD/scrapping_platforms.py --platform ${{ matrix.platform }} && break
            status=$?
            echo "⚠️ Failed with status $status. Sleeping 120s..."
            if [ $attempt -lt 3 ]; then
              sleep 120
            else
              exit $status
            fi
          done

      - name: Done
        run: echo "✅ Scrape done for ${{ matrix.platform }}"
